// src/components/PostureDock.tsx
import { ChevronLeft, ChevronRight, Pause, Play } from 'lucide-react'
import { motion } from 'motion/react'
import { Fragment, useEffect, useMemo, useRef } from 'react'
import { postureKey } from '@/content/postures'
import { useT } from '@/i18n'
import { cn } from '@/lib/cn'
import { postureSegments } from '@/sequence/build'
import { useSession } from '@/state/session'
import { PostureIcon } from './PostureIcon'
import { Tooltip } from './ui/primitives'

/**
 * The bottom dock: which rak'ah you're in, the movements of that rak'ah, and
 * quiet manual controls. Mirrors the mockup on laptops; condenses on phones.
 */
export function PostureDock({ following }: { following: boolean }) {
  const t = useT()
  const { sequence, index, phase, autoplay, handsFree, next, prev, goTo, setAutoplay } = useSession()
  const segments = useMemo(() => postureSegments(sequence.steps), [sequence])
  const praying = phase === 'praying'
  const step = sequence.steps[index]!
  const rakah = phase === 'ready' ? 1 : phase === 'complete' ? sequence.rakahs : step.rakah
  const inRakah = segments.filter((s) => s.rakah === rakah)
  const activeRef = useRef<HTMLButtonElement>(null)
  const listRef = useRef<HTMLOListElement>(null)

  // Keep the current movement in view on narrow screens. (Scroll only the
  // list — scrollIntoView would also nudge the page.)
  useEffect(() => {
    const list = listRef.current
    const item = activeRef.current
    if (!list || !item) return
    const left = item.offsetLeft - list.clientWidth / 2 + item.clientWidth / 2
    list.scrollTo({ left: getComputedStyle(list).direction === 'rtl' ? left - list.scrollWidth + list.clientWidth : left, behavior: 'smooth' })
  }, [index])

  return (
    <div className="glass mx-auto flex w-full max-w-[52rem] items-stretch gap-1 rounded-[1.35rem] p-1.5 shadow-[0_20px_60px_-20px_rgba(0,0,0,0.6)] sm:gap-2 sm:p-2">
      {/* Rak'ah */}
      <div className="flex shrink-0 flex-col justify-center gap-1.5 py-1 pr-2 pl-2.5 sm:pr-4 sm:pl-3.5">
        <div className="text-sm leading-none font-semibold text-ink">{t('dock.rakah')}</div>
        <div className="tabular text-sm leading-none text-ink-muted">{t('dock.rakahOf', { r: rakah, n: sequence.rakahs })}</div>
        <div className="flex gap-1" aria-hidden>
          {Array.from({ length: sequence.rakahs }, (_, i) => (
            <span key={i} className={cn('h-1 w-3 rounded-full transition-colors duration-500', i + 1 < rakah || phase === 'complete' ? 'bg-mint/70' : i + 1 === rakah && praying ? 'bg-mint' : 'bg-white/10')} />
          ))}
        </div>
      </div>
      <div className="my-2 w-px shrink-0 bg-line" />

      {/* Movements of this rak'ah */}
      <ol ref={listRef} className="relative flex min-w-0 flex-1 items-center overflow-x-auto [mask-image:linear-gradient(to_right,transparent,black_14px,black_calc(100%-14px),transparent)] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
        {inRakah.map((seg, i) => {
          const active = praying && index >= seg.start && index < seg.end
          const done = phase === 'complete' || (praying && index >= seg.end)
          const key = postureKey(seg.posture)
          const label = t(`posture.${key}`)
          return (
            <Fragment key={`${seg.rakah}-${seg.start}`}>
              {i > 0 && <li aria-hidden className={cn('h-px w-2 shrink-0 transition-colors sm:w-3', done || active ? 'bg-mint/40' : 'bg-white/10')} />}
              <li className="shrink-0">
                <Tooltip content={<span><span className="text-ink">{label}</span> · {t(`hint.${key}`)}</span>} side="top">
                  <button
                    ref={active ? activeRef : undefined}
                    onClick={() => goTo(seg.start)}
                    aria-current={active ? 'step' : undefined}
                    className={cn(
                      'relative flex h-[3.6rem] cursor-pointer flex-col items-center justify-center gap-1 rounded-2xl px-2.5 transition-colors duration-300 sm:h-16 sm:min-w-[4.5rem] sm:px-3',
                      active ? 'text-mint' : done ? 'text-ink-soft hover:text-ink' : 'text-ink-muted/80 hover:text-ink-soft',
                    )}
                  >
                    {active && (
                      <motion.span
                        layoutId="dock-active"
                        className="absolute inset-0 rounded-2xl border border-mint/25 bg-mint/[0.09] shadow-[inset_0_1px_0_rgb(255_255_255/0.06),0_0_28px_-10px_color-mix(in_oklab,var(--accent)_80%,transparent)]"
                        transition={{ type: 'spring', bounce: 0.15, duration: 0.55 }}
                      />
                    )}
                    <PostureIcon posture={seg.posture} className="relative size-6 sm:size-7" />
                    <span className={cn('relative text-sm leading-none font-medium whitespace-nowrap sm:text-xs', !active && 'max-sm:sr-only')}>{label}</span>
                  </button>
                </Tooltip>
              </li>
            </Fragment>
          )
        })}
      </ol>

      <div className="my-2 w-px shrink-0 bg-line" />
      {/* Controls */}
      <div className="flex shrink-0 items-center gap-0.5 pr-0.5 sm:gap-1 sm:pr-1">
        <IconButton label={t('dock.previous')} onClick={prev} disabled={phase === 'ready' || (praying && index === 0)} className="max-sm:hidden">
          <ChevronLeft className="size-5 rtl:rotate-180" />
        </IconButton>
        {handsFree && following ? (
          <div className="flex h-10 items-center gap-1.5 px-1.5 text-sm text-ink-muted max-sm:hidden">
            <span className="size-1.5 animate-breathe rounded-full bg-mint" />
            {t('dock.following')}
          </div>
        ) : (
          <IconButton label={autoplay ? t('dock.pause') : t('dock.guide')} onClick={() => setAutoplay(!autoplay)} active={autoplay} disabled={phase === 'complete'}>
            {autoplay ? <Pause className="size-[18px] fill-current" /> : <Play className="size-[18px] fill-current" />}
          </IconButton>
        )}
        <IconButton label={t('dock.next')} onClick={next} disabled={phase === 'complete'}>
          <ChevronRight className="size-5 rtl:rotate-180" />
        </IconButton>
      </div>
    </div>
  )
}

function IconButton({
  label,
  children,
  active,
  className,
  ...props
}: React.ComponentProps<'button'> & { label: string; active?: boolean }) {
  return (
    <Tooltip content={label} side="top">
      <button
        {...props}
        aria-label={label}
        className={cn(
          'flex size-10 cursor-pointer items-center justify-center rounded-full text-ink-soft transition-colors hover:bg-white/[0.07] hover:text-ink disabled:pointer-events-none disabled:opacity-30',
          active && 'bg-mint/[0.12] text-mint',
          className,
        )}
      >
        {children}
      </button>
    </Tooltip>
  )
}

// src/components/PostureDock.svelte
<script lang="ts">
  import ChevronLeft from '@lucide/svelte/icons/chevron-left'
  import ChevronRight from '@lucide/svelte/icons/chevron-right'
  import Pause from '@lucide/svelte/icons/pause'
  import Play from '@lucide/svelte/icons/play'
  import { postureKey } from '@/content/postures'
  import { t } from '@/i18n/i18n.svelte'
  import { postureSegments } from '@/sequence/build'
  import { session } from '@/state/session.svelte'
  import PostureIcon from './PostureIcon.svelte'

  let { following }: { following: boolean } = $props()

  const segments = $derived(postureSegments(session.sequence.steps))
  const praying = $derived(session.phase === 'praying')
  const rakah = $derived(session.phase === 'ready' ? 1 : session.phase === 'complete' ? session.sequence.rakahs : session.step.rakah)
  const inRakah = $derived(segments.filter((s) => s.rakah === rakah))
  let list = $state<HTMLOListElement>()

  // Keep the current movement in view on narrow screens (scroll only the list).
  $effect(() => {
    void session.index
    const item = list?.querySelector<HTMLElement>('[aria-current="step"]')
    if (!list || !item) return
    // Visual offsets work the same left-to-right and right-to-left.
    const box = list.getBoundingClientRect()
    const at = item.getBoundingClientRect()
    list.scrollTo({ left: list.scrollLeft + (at.left - box.left) - (box.width - at.width) / 2, behavior: 'smooth' })
  })

  // One highlight that slides from movement to movement (it jumps when a new rak'ah begins).
  let pill = $state({ x: 0, w: 0, on: false, glide: false })
  let pillRakah = 0
  function place() {
    const item = list?.querySelector<HTMLElement>('[aria-current="step"]')
    const glide = pill.on && pillRakah === rakah
    pillRakah = rakah
    pill = item ? { x: item.offsetLeft, w: item.offsetWidth, on: true, glide } : { ...pill, on: false, glide: false }
  }
  $effect(() => {
    void session.index
    void inRakah
    void praying
    const id = requestAnimationFrame(place)
    return () => cancelAnimationFrame(id)
  })
  $effect(() => {
    if (!list) return
    const ro = new ResizeObserver(() => place())
    ro.observe(list)
    return () => ro.disconnect()
  })
</script>

<div class="dock">
  <div class="rakah">
    <span class="label">{t('dock.rakah')}</span>
    <span class="of num">{t('dock.rakahOf', { r: rakah, n: session.sequence.rakahs })}</span>
    <span class="bars" aria-hidden="true">
      {#each { length: session.sequence.rakahs } as _, i (i)}
        <i class:done={i + 1 < rakah || session.phase === 'complete'} class:now={i + 1 === rakah && praying}></i>
      {/each}
    </span>
  </div>

  <ol bind:this={list} class="moves">
    <li class="pill" class:on={pill.on} class:glide={pill.glide} style:translate="{pill.x}px 0" style:width="{pill.w}px" aria-hidden="true"></li>
    {#each inRakah as seg (`${seg.rakah}-${seg.start}`)}
      {@const active = praying && session.index >= seg.start && session.index < seg.end}
      {@const done = session.phase === 'complete' || (praying && session.index >= seg.end)}
      {@const key = postureKey(seg.posture)}
      <li>
        <button
          type="button"
          class="move"
          class:done
          aria-current={active ? 'step' : undefined}
          title="{t(`posture.${key}`)} · {t(`hint.${key}`)}"
          onclick={() => session.goTo(seg.start)}
        >
          <PostureIcon posture={seg.posture} size={26} />
          <span class="name" class:sr-only-phone={!active}>{t(`posture.${key}`)}</span>
        </button>
      </li>
    {/each}
  </ol>

  <div class="controls">
    <button type="button" class="btn quiet icon lg hide-phone" aria-label={t('dock.previous')} title={t('dock.previous')} onclick={() => session.prev()} disabled={session.phase === 'ready' || (praying && session.index === 0)}>
      <ChevronLeft size={20} class="flip-rtl" />
    </button>
    {#if session.handsFree && following}
      <span class="following hide-phone"><i aria-hidden="true"></i>{t('dock.following')}</span>
    {:else}
      <button type="button" class="btn quiet icon lg" aria-pressed={session.autoplay} aria-label={session.autoplay ? t('dock.pause') : t('dock.guide')} title={session.autoplay ? t('dock.pause') : t('dock.guide')} onclick={() => session.setAutoplay(!session.autoplay)} disabled={session.phase === 'complete'}>
        {#if session.autoplay}<Pause size={18} fill="currentColor" />{:else}<Play size={18} fill="currentColor" />{/if}
      </button>
    {/if}
    <button type="button" class="btn quiet icon lg" aria-label={t('dock.next')} title={t('dock.next')} onclick={() => session.next()} disabled={session.phase === 'complete'}>
      <ChevronRight size={20} class="flip-rtl" />
    </button>
  </div>
</div>

<style>
  .dock {
    display: flex;
    align-items: stretch;
    gap: var(--space-2);
    width: 100%;
    padding: 6px;
    border-radius: var(--radius-surface);
    background: var(--surface);
  }
  .rakah {
    flex: none;
    display: flex;
    flex-direction: column;
    justify-content: center;
    gap: 4px;
    padding-inline: 10px 14px;
    border-inline-end: 1px solid var(--line);
  }
  .label {
    font-size: 14px;
    font-weight: 600;
    line-height: 1.2;
  }
  .of {
    font-size: 12px;
    line-height: 1.2;
    color: var(--ink-muted);
  }
  .bars {
    display: flex;
    gap: 3px;
  }
  .bars i {
    width: 12px;
    height: 4px;
    border-radius: var(--radius-inset);
    background: var(--line-strong);
    transition:
      background var(--dur-standard) var(--ease-out),
      width 420ms cubic-bezier(0.32, 0.72, 0, 1);
  }
  .bars i.now {
    width: 20px;
  }
  .bars i.done {
    background: var(--ink-muted);
  }
  .bars i.now {
    background: var(--brand);
  }
  .moves {
    position: relative;
    flex: 1;
    min-width: 0;
    display: flex;
    align-items: center;
    gap: 2px;
    margin: 0;
    padding: 0;
    list-style: none;
    overflow-x: auto;
    scrollbar-width: none;
    scroll-padding-inline: 8px;
    /* Moves that don't fit fade at the edges instead of being cut mid-word. */
    mask-image: linear-gradient(to right, transparent, #000 10px, #000 calc(100% - 10px), transparent);
  }
  .moves::-webkit-scrollbar {
    display: none;
  }
  li {
    flex: none;
  }
  .pill {
    position: absolute;
    top: 50%;
    left: 0;
    height: 64px;
    margin-top: -32px;
    border-radius: var(--radius-control);
    background: var(--brand-tint);
    opacity: 0;
    pointer-events: none;
    transition: opacity var(--dur-standard) var(--ease-out);
  }
  .pill.on {
    opacity: 1;
  }
  .pill.glide {
    transition:
      translate 460ms cubic-bezier(0.32, 0.72, 0, 1),
      width 460ms cubic-bezier(0.32, 0.72, 0, 1),
      opacity var(--dur-standard) var(--ease-out);
  }
  .move {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 4px;
    min-width: 68px;
    height: 64px;
    padding: 0 8px;
    border: 0;
    border-radius: var(--radius-control);
    background: transparent;
    color: var(--ink-faint);
    transition:
      background var(--dur-fast) var(--ease-out),
      color var(--dur-standard) var(--ease-out);
  }
  .move:hover {
    background: var(--surface-hover);
    color: var(--ink-muted);
  }
  .move.done {
    color: var(--ink-muted);
  }
  .move[aria-current='step'] {
    background: transparent;
    color: var(--brand);
  }
  .name {
    font-size: 12px;
    font-weight: 500;
    line-height: 1;
    white-space: nowrap;
  }
  .move[aria-current='step'] .name {
    font-weight: 600;
  }
  .controls {
    flex: none;
    display: flex;
    align-items: center;
    gap: 2px;
    padding-inline-start: 6px;
    border-inline-start: 1px solid var(--line);
  }
  .controls .btn {
    color: var(--ink);
  }
  .controls .btn:hover {
    background: var(--surface-hover);
  }
  .controls .btn[aria-pressed='true'] {
    background: var(--brand-tint);
    color: var(--brand);
  }
  .following {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding-inline: 8px;
    font-size: 13px;
    color: var(--ink-muted);
    white-space: nowrap;
  }
  .following i {
    width: 6px;
    height: 6px;
    border-radius: var(--radius-full);
    background: var(--brand);
  }
  @media (max-width: 639px) {
    .hide-phone {
      display: none;
    }
    .rakah {
      padding-inline: 6px 10px;
    }
    .rakah .label {
      display: none;
    }
    .move {
      min-width: 52px;
      height: 56px;
    }
    .pill {
      height: 56px;
      margin-top: -28px;
    }
    .sr-only-phone {
      position: absolute;
      width: 1px;
      height: 1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
    }
  }
</style>
