// src/components/SettingsSheet.tsx
import { Check, MapPin } from 'lucide-react'
import { quranCredit } from '@/content/lines'
import { detectLocale, LOCALES, useLocale, useT, type Locale } from '@/i18n'
import { cn } from '@/lib/cn'
import { methodLabel } from '@/lib/prayer-times'
import type { PrayerClock } from '@/lib/use-prayer-clock'
import { display, useSession, type Pace, type TextSize } from '@/state/session'
import { CHARACTERS } from './stage/characters'
import { Sheet } from './ui/Sheet'
import { Kbd, Segmented, Switch } from './ui/primitives'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h3 className="text-[11px] font-medium tracking-[0.14em] text-ink-muted uppercase">{title}</h3>
      {children}
    </section>
  )
}

export function SettingsSheet({ open, onOpenChange, clock }: { open: boolean; onOpenChange: (o: boolean) => void; clock: PrayerClock }) {
  const t = useT()
  const locale = useLocale()
  const settings = useSession((s) => s.settings)
  const update = useSession((s) => s.updateSettings)
  const demo = useSession((s) => s.demo)
  const setDemo = useSession((s) => s.setDemo)
  const show = display(settings, locale)
  const { place } = clock

  const languages: { value: 'auto' | Locale; label: string; hint?: string }[] = [
    { value: 'auto', label: t('settings.auto'), hint: LOCALES[detectLocale()].name },
    ...(Object.entries(LOCALES) as [Locale, (typeof LOCALES)[Locale]][]).map(([value, l]) => ({ value, label: l.name })),
  ]

  return (
    <Sheet open={open} onOpenChange={onOpenChange} title={t('settings.title')}>
      <div className="space-y-6 pb-2">
        <Section title={t('settings.language')}>
          <div className="grid grid-cols-2 gap-1.5" role="radiogroup">
            {languages.map((l) => {
              const active = settings.locale === l.value
              return (
                <button
                  key={l.value}
                  role="radio"
                  aria-checked={active}
                  onClick={() => update({ locale: l.value })}
                  className={cn(
                    'flex cursor-pointer items-center justify-between gap-2 rounded-xl border px-3 py-2.5 text-start text-sm transition-colors',
                    active ? 'border-mint/45 bg-mint/[0.08] text-ink' : 'border-line text-ink-soft hover:bg-white/[0.04]',
                  )}
                >
                  <span className="min-w-0">
                    <span className="block truncate">{l.label}</span>
                    {l.hint && <span className="block truncate text-[11px] text-ink-muted">{l.hint}</span>}
                  </span>
                  {active && <Check className="size-4 shrink-0 text-mint" />}
                </button>
              )
            })}
          </div>
        </Section>

        <Section title={t('settings.show')}>
          <Switch label={t('settings.transliteration')} checked={show.transliteration} onCheckedChange={(v) => update({ transliteration: v })} />
          <Switch label={t('settings.translation')} checked={show.translation} onCheckedChange={(v) => update({ translation: v })} />
          <Switch label={t('settings.arabic')} checked={show.arabic} onCheckedChange={(v) => update({ arabic: v })} />
        </Section>

        <Section title={t('settings.size')}>
          <Segmented<TextSize>
            id="size"
            value={settings.textSize}
            options={[
              { value: 'm', label: <span className="text-sm">A</span> },
              { value: 'l', label: <span className="text-base">A</span> },
              { value: 'xl', label: <span className="text-lg">A</span> },
            ]}
            onChange={(v) => update({ textSize: v })}
          />
        </Section>

        <Section title={t('settings.pace')}>
          <Segmented<Pace>
            id="pace"
            value={settings.pace}
            options={[
              { value: 'slow', label: t('settings.slow') },
              { value: 'normal', label: t('settings.normal') },
              { value: 'brisk', label: t('settings.brisk') },
            ]}
            onChange={(v) => update({ pace: v })}
          />
        </Section>

        {CHARACTERS.length > 1 && (
          <Section title={t('settings.companion')}>
            <div className="grid grid-cols-2 gap-2">
              {CHARACTERS.map((c) => {
                const active = settings.characterId === c.id
                return (
                  <button
                    key={c.id}
                    onClick={() => update({ characterId: c.id })}
                    aria-pressed={active}
                    className={cn(
                      'group relative flex cursor-pointer flex-col items-center overflow-hidden rounded-2xl border p-2 pb-2.5 transition-colors',
                      active ? 'border-mint/50 bg-mint/[0.08]' : 'border-line hover:bg-white/[0.04]',
                    )}
                  >
                    {c.thumbnail ? (
                      <img src={c.thumbnail} alt="" className="aspect-square w-full rounded-xl object-cover" loading="lazy" />
                    ) : (
                      <div className="aspect-square w-full rounded-xl bg-white/[0.04]" />
                    )}
                    <span className={cn('mt-2 text-sm', active ? 'text-ink' : 'text-ink-soft')}>{c.name}</span>
                  </button>
                )
              })}
            </div>
          </Section>
        )}

        <Section title={t('hf.button')}>
          <Switch label={t('settings.demo')} checked={demo} onCheckedChange={setDemo} />
          <Switch label={t('settings.sounds')} checked={settings.sounds} onCheckedChange={(v) => update({ sounds: v })} />
        </Section>

        <Section title={t('settings.times')}>
          <div className="flex items-center justify-between gap-3 text-sm">
            <span className="flex min-w-0 items-center gap-2 text-ink-soft">
              <MapPin className="size-4 shrink-0 text-ink-muted" />
              <span className="truncate">
                {place.source === 'gps' ? t('settings.yourLocation') : t('settings.approx', { place: place.label ?? t('settings.yourZone') })}
              </span>
            </span>
            {place.source !== 'gps' && (
              <button onClick={clock.useMyLocation} disabled={clock.locating} className="shrink-0 cursor-pointer text-xs font-medium text-mint hover:underline disabled:opacity-50">
                {clock.locating ? t('settings.locating') : t('settings.useLocation')}
              </button>
            )}
          </div>
          <p className="text-xs text-ink-faint">{t('settings.method', { method: methodLabel() })}</p>
        </Section>

        <div className="hidden flex-wrap gap-x-3 gap-y-1.5 border-t border-line pt-4 text-xs text-ink-muted md:flex">
          <span className="flex items-center gap-1.5"><Kbd>Space</Kbd> {t('settings.keys.next')}</span>
          <span className="flex items-center gap-1.5"><Kbd>←</Kbd> {t('settings.keys.back')}</span>
          <span className="flex items-center gap-1.5"><Kbd>P</Kbd> {t('settings.keys.auto')}</span>
          <span className="flex items-center gap-1.5"><Kbd>H</Kbd> {t('settings.keys.hf')}</span>
        </div>
        <p className="text-[11px] leading-relaxed text-ink-faint">{t('settings.sources', { credit: quranCredit(locale) })}</p>
      </div>
    </Sheet>
  )
}

// src/components/SettingsSheet.svelte
<script lang="ts">
  import Check from '@lucide/svelte/icons/check'
  import MapPin from '@lucide/svelte/icons/map-pin'
  import BACKDROPS from '@/content/backdrops.json'
  import { quranCredit } from '@/content/lines'
  import { detectLocale, LOCALES, OFFERED } from '@/i18n'
  import { i18n, t } from '@/i18n/i18n.svelte'
  import { CRESCENT, PALETTES } from '@/lib/brand'
  import { clock } from '@/lib/prayer-clock.svelte'
  import { methodLabel } from '@/lib/prayer-times'
  import { display, session, type TextSize, type Theme } from '@/state/session.svelte'
  import { CHARACTERS } from './stage/characters'
  import Segmented from './ui/Segmented.svelte'
  import Sheet from './ui/Sheet.svelte'
  import Switch from './ui/Switch.svelte'

  /**
   * What the learner can change: the companion and how things look. Everything else (spoken
   * instructions, following the recitation, the pace) is part of praying with PrayAlong.
   */
  let { open = $bindable(false) }: { open: boolean } = $props()

  const settings = $derived(session.settings)
  const update = (patch: Parameters<typeof session.updateSettings>[0]) => session.updateSettings(patch)
  const show = $derived(display(settings, i18n.locale))
  const languages = $derived([
    { value: 'auto' as const, label: t('settings.auto'), hint: LOCALES[detectLocale()].name },
    ...OFFERED.map((value) => ({ value, label: LOCALES[value].name, hint: '' })),
  ])
  const photo = $derived(BACKDROPS[session.prayer])
  const about = $derived([
    { label: t('about.recitations'), value: t('about.recitationsBy') },
    ...(i18n.locale === 'ar' ? [] : [{ label: t('about.translation'), value: quranCredit(i18n.locale) }]),
    { label: t('about.reciter'), value: t('qari.name') },
    { label: t('about.voice'), value: t('about.voiceBy') },
  ])
</script>

<Sheet bind:open title={t('settings.title')}>
  <div class="sections">
    <section>
      <h3>{t('settings.companion')}</h3>
      <div class="cards">
        {#each CHARACTERS as c (c.id)}
          <button type="button" class="card" aria-pressed={settings.characterId === c.id} onclick={() => update({ characterId: c.id })}>
            <img src={c.thumbnail} alt="" width="160" height="160" loading="lazy" />
            <span>{t(c.nameKey)}</span>
          </button>
        {/each}
      </div>
      <p class="soon"><span>{t('companion.auto')}</span><span class="tag">{t('ui.soon')}</span></p>
    </section>

    <section>
      <h3>{t('settings.display')}</h3>
      <div class="field">
        <span class="label">{t('settings.size')}</span>
        <Segmented
          label={t('settings.size')}
          value={settings.textSize}
          options={[
            { value: 'm', label: 'A', size: 13 },
            { value: 'l', label: 'A', size: 16 },
            { value: 'xl', label: 'A', size: 19 },
          ]}
          onchange={(v) => update({ textSize: v as TextSize })}
        />
      </div>
      <div class="group">
        <Switch label={t('settings.transliteration')} checked={show.transliteration} onchange={(v) => update({ transliteration: v })} />
        <Switch label={t('settings.translation')} checked={show.translation} onchange={(v) => update({ translation: v })} />
        <Switch label={t('settings.arabic')} checked={show.arabic} onchange={(v) => update({ arabic: v })} />
      </div>
      <div class="field">
        <span class="label">{t('settings.appearance')}</span>
        <Segmented
          label={t('settings.appearance')}
          value={settings.theme}
          options={[
            { value: 'system', label: t('settings.system') },
            { value: 'light', label: t('settings.light') },
            { value: 'dark', label: t('settings.dark') },
          ]}
          onchange={(v) => update({ theme: v as Theme })}
        />
      </div>
      <div class="field">
        <span class="label">{t('settings.palette')}</span>
        <div class="palettes" role="radiogroup" aria-label={t('settings.palette')}>
          {#each PALETTES as p (p)}
            <button type="button" role="radio" aria-checked={settings.palette === p} data-palette={p} onclick={() => update({ palette: p })}>
              <svg viewBox="-8 -8 64 64" aria-hidden="true"><rect x="-8" y="-8" width="64" height="64" rx="14" /><path d={CRESCENT} /></svg>
              <span>{t(`palette.${p}`)}</span>
              {#if p === 'plum' || p === 'indigo'}<small>{t(`palette.${p}Hint`)}</small>{/if}
            </button>
          {/each}
        </div>
      </div>
    </section>

    <section>
      <h3>{t('settings.language')}</h3>
      <div class="langs" role="radiogroup" aria-label={t('settings.language')}>
        {#each languages as l (l.value)}
          <button type="button" role="radio" aria-checked={settings.locale === l.value} onclick={() => update({ locale: l.value })}>
            <span>
              <span class="name">{l.label}</span>
              {#if l.hint}<small>{l.hint}</small>{/if}
            </span>
            {#if settings.locale === l.value}<Check size={16} />{/if}
          </button>
        {/each}
      </div>
    </section>

    <section>
      <h3>{t('settings.times')}</h3>
      <div class="place">
        <span><MapPin size={16} />{clock.place.source === 'gps' ? t('settings.yourLocation') : t('settings.approx', { place: clock.place.label ?? t('settings.yourZone') })}</span>
        {#if clock.place.source !== 'gps'}
          <button type="button" class="btn quiet sm" onclick={clock.useMyLocation} disabled={clock.locating}>{clock.locating ? t('settings.locating') : t('settings.useLocation')}</button>
        {/if}
      </div>
      <p class="fine">{t('settings.method', { method: methodLabel() })}</p>
    </section>

    <section class="about">
      <h3>{t('settings.about')}</h3>
      <dl>
        {#each about as row (row.label)}
          <div><dt>{row.label}</dt><dd>{row.value}</dd></div>
        {/each}
        <div>
          <dt>{t('about.photo')}</dt>
          <dd><a href={photo.page} target="_blank" rel="noreferrer">{t('about.photoBy', { what: photo.what, by: photo.by })}</a></dd>
        </div>
      </dl>
    </section>
  </div>
</Sheet>

<style>
  .sections {
    display: grid;
    gap: var(--space-6);
  }
  section {
    display: grid;
    gap: var(--space-3);
  }
  h3 {
    font-size: 13px;
    font-weight: 600;
    line-height: 1.3;
    color: var(--ink-muted);
  }
  .field {
    display: grid;
    gap: 6px;
  }
  .label {
    font-size: 14px;
    font-weight: 500;
  }
  /* Switches read as one list: a surface, rows split by hairlines. */
  .group {
    padding: 2px 14px;
    border-radius: var(--radius-surface);
    background: var(--surface);
  }
  .group :global(.row + .row) {
    border-top: 1px solid var(--line);
  }
  .soon {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--space-4);
    font-size: 14px;
    color: var(--ink-muted);
  }
  .cards {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: var(--space-2);
  }
  .card {
    display: grid;
    gap: var(--space-2);
    justify-items: center;
    padding: 8px 8px 10px;
    border: 0;
    border-radius: var(--radius-surface);
    background: var(--surface);
    font-size: 14px;
    font-weight: 500;
    transition:
      background var(--dur-standard) var(--ease-out),
      color var(--dur-standard) var(--ease-out);
  }
  .card:hover {
    background: var(--surface-hover);
  }
  .card img {
    width: 100%;
    height: auto;
    aspect-ratio: 1;
    object-fit: cover;
    border-radius: 8px;
    background: var(--paper);
    transition: scale var(--dur-standard) var(--ease-out);
  }
  .card[aria-pressed='true'] {
    background: var(--brand-tint);
    color: var(--brand);
    font-weight: 600;
  }
  /* Each swatch is the app icon in its palette: the tile keeps its colour in both themes. */
  .palettes {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: var(--space-2);
  }
  .palettes button {
    display: grid;
    justify-items: center;
    align-content: start;
    gap: 2px;
    padding: 10px 4px 8px;
    border: 0;
    border-radius: var(--radius-surface);
    background: var(--surface);
    font-size: 13px;
    line-height: 1.3;
    transition:
      background var(--dur-standard) var(--ease-out),
      color var(--dur-standard) var(--ease-out);
  }
  .palettes button:hover {
    background: var(--surface-hover);
  }
  .palettes button[aria-checked='true'] {
    background: var(--brand-tint);
    color: var(--brand);
    font-weight: 600;
  }
  .palettes svg {
    width: 34px;
    height: 34px;
    margin-bottom: 4px;
    transition: scale 420ms cubic-bezier(0.34, 1.4, 0.64, 1);
  }
  .palettes button[aria-checked='true'] svg {
    scale: 1.08;
  }
  .palettes rect {
    fill: var(--p-700);
  }
  .palettes path {
    fill: var(--p-50);
  }
  .palettes small {
    font-size: 11px;
    font-weight: 400;
    color: var(--ink-muted);
  }
  .langs {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: var(--space-2);
  }
  .langs button {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--space-2);
    min-height: 52px;
    padding: 6px 14px;
    border: 0;
    border-radius: var(--radius-control);
    background: var(--surface);
    text-align: start;
    font-size: 14px;
    transition:
      background var(--dur-standard) var(--ease-out),
      color var(--dur-standard) var(--ease-out);
  }
  .langs button:hover {
    background: var(--surface-hover);
  }
  .langs button[aria-checked='true'] {
    background: var(--brand-tint);
    color: var(--brand);
    font-weight: 600;
  }
  .langs small {
    display: block;
    font-size: 12px;
    font-weight: 400;
    color: var(--ink-muted);
  }
  .place {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--space-3);
    font-size: 15px;
  }
  .place > span {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    min-width: 0;
  }
  .fine {
    margin-top: -6px;
    font-size: 13px;
    line-height: 1.45;
    color: var(--ink-muted);
  }
  /* About: label and value, one line each. */
  .about {
    padding-top: var(--space-5);
    border-top: 1px solid var(--line);
  }
  dl {
    display: grid;
    gap: var(--space-3);
    margin: 0;
  }
  dl div {
    display: grid;
    grid-template-columns: 9em 1fr;
    gap: var(--space-3);
    font-size: 13px;
    line-height: 1.45;
  }
  dt {
    color: var(--ink-muted);
  }
  dd {
    margin: 0;
    color: var(--ink);
  }
  dd a {
    color: inherit;
    text-decoration: underline;
    text-decoration-color: var(--line-strong);
    text-underline-offset: 3px;
    transition: text-decoration-color var(--dur-fast) var(--ease-out);
  }
  dd a:hover {
    text-decoration-color: currentColor;
  }
</style>
