// src/components/SetupSheet.svelte
<script lang="ts">
  import CircleCheck from '@lucide/svelte/icons/circle-check'
  import Footprints from '@lucide/svelte/icons/footprints'
  import Hand from '@lucide/svelte/icons/hand'
  import Mic from '@lucide/svelte/icons/mic'
  import RefreshCw from '@lucide/svelte/icons/refresh-cw'
  import Smartphone from '@lucide/svelte/icons/smartphone'
  import SwitchCamera from '@lucide/svelte/icons/switch-camera'
  import { handsFree } from '@/handsfree/hands-free.svelte'
  import { isFallback } from '@/handsfree/types'
  import { t } from '@/i18n/i18n.svelte'
  import { session } from '@/state/session.svelte'
  import { voice } from '@/voice/voice.svelte'
  import CameraPreview from './CameraPreview.svelte'
  import { fallbackText, statusText } from './HandsFree.svelte'
  import Skeleton from './Skeleton.svelte'
  import Sheet from './ui/Sheet.svelte'

  /** Getting hands-free right the first time: placement, a live framing check, then begin. */
  let { open = $bindable(false), onbegin }: { open: boolean; onbegin: () => void } = $props()

  const fallback = $derived(fallbackText(handsFree.status))
  const failed = $derived(isFallback(handsFree.status))
  // While the browser asks for the camera and microphone, the camera is about to start.
  const waiting = $derived(handsFree.status === 'off' ? 'starting' : handsFree.status)
  const listener = $derived(
    voice.asr === 'off' ? null : voice.asr === 'loading' ? t('voice.loading', { p: voice.progress }) : t(`voice.${voice.asr}`),
  )
  const mirror = $derived(handsFree.facingMode === 'user')
  const check = $derived(
    handsFree.status !== 'watching'
      ? { tone: '', text: statusText(waiting) }
      : handsFree.framing === 'full'
        ? { tone: 'ok', text: t('setup.seeYou') }
        : handsFree.framing === 'partial'
          ? { tone: 'warn', text: t('hf.msg.noPerson') }
          : { tone: '', text: t('setup.lookingForYou') },
  )
  const steps = [
    { icon: Smartphone, key: 'setup.step1' },
    { icon: Footprints, key: 'setup.step2' },
    { icon: Hand, key: 'setup.step3' },
  ] as const
</script>

<Sheet bind:open title={t('setup.title')} description={t('setup.body')}>
  <div class="frame">
    {#if handsFree.stream}
      <CameraPreview stream={handsFree.stream} {mirror} />
      <Skeleton keypoints={handsFree.keypoints} {mirror} />
      <button type="button" class="btn icon flip" aria-label="Switch camera" onclick={handsFree.flip}><SwitchCamera size={18} /></button>
    {:else}
      <p class="empty">{fallback ?? statusText(waiting)}</p>
    {/if}
    <p class="check tag {check.tone}">
      {#if check.tone === 'ok'}<CircleCheck size={16} />{/if}
      {check.text}
    </p>
  </div>

  {#if handsFree.engineLabel && handsFree.status === 'watching'}
    <p class="engine">{handsFree.engineLabel} · {t('hf.private')}</p>
  {/if}

  <ol class="steps">
    {#each steps as s, i (s.key)}
      <li style:--i={i}><span class="disc"><s.icon size={16} /></span>{t(s.key)}</li>
    {/each}
  </ol>

  {#if listener}
    <p class="listener" class:warn={voice.asr === 'blocked' || voice.asr === 'error'}>
      <Mic size={15} />{listener}
      {#if voice.asr === 'loading'}<span class="progress" aria-hidden="true"><i style:width="{voice.progress}%"></i></span>{/if}
    </p>
  {/if}

  <div class="actions">
    <button type="button" class="btn primary lg" onclick={onbegin}>
      {session.phase !== 'ready' ? t('setup.done') : failed ? t('setup.withoutCamera') : t('ready.begin', { prayer: t(`prayer.${session.prayer}`) })}
    </button>
    {#if failed && handsFree.status !== 'no-model'}
      <button type="button" class="btn quiet" onclick={handsFree.retry}><RefreshCw size={16} />{t('hf.retry')}</button>
    {/if}
  </div>
</Sheet>

<style>
  .frame {
    position: relative;
    overflow: hidden;
    margin-top: var(--space-2);
    border-radius: var(--radius-surface);
    background: var(--media);
    aspect-ratio: 4 / 5;
  }
  .frame :global(video) {
    height: 100%;
  }
  .empty {
    display: grid;
    place-items: center;
    height: 100%;
    padding: var(--space-5);
    text-align: center;
    font-size: 14px;
    color: var(--on-photo);
  }
  .flip {
    position: absolute;
    top: 12px;
    inset-inline-end: 12px;
    background: var(--raised);
  }
  .check {
    position: absolute;
    inset: auto 12px 12px 12px;
    justify-content: center;
    min-height: 40px;
    background: var(--raised);
    color: var(--ink);
    font-size: 14px;
  }
  .check.ok {
    color: var(--state-correct);
  }
  .check.warn {
    color: var(--state-khafi);
  }
  .engine {
    margin-top: var(--space-2);
    text-align: center;
    font-size: 12px;
    color: var(--ink-muted);
  }
  .steps {
    display: grid;
    gap: var(--space-3);
    margin: var(--space-4) 0 0;
    padding: 0;
    list-style: none;
    font-size: 15px;
  }
  .steps li {
    display: flex;
    align-items: center;
    gap: var(--space-3);
    animation: rise 520ms var(--ease-out) both;
    animation-delay: calc(120ms + var(--i) * 70ms);
  }
  @keyframes rise {
    from {
      opacity: 0;
      translate: 0 8px;
    }
  }
  .listener {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 6px 8px;
    margin-top: var(--space-4);
    font-size: 13px;
    color: var(--ink-muted);
  }
  .listener.warn {
    color: var(--state-khafi);
  }
  .progress {
    flex-basis: 100%;
    height: 3px;
    border-radius: var(--radius-full);
    background: var(--surface);
    overflow: hidden;
  }
  .progress i {
    display: block;
    height: 100%;
    background: var(--brand);
    transition: width var(--dur-standard) var(--ease-out);
  }
  .disc {
    display: grid;
    place-items: center;
    flex: none;
    width: 32px;
    height: 32px;
    border-radius: var(--radius-full);
    background: var(--brand-tint);
    color: var(--brand);
  }
  .actions {
    display: grid;
    gap: var(--space-2);
    margin-top: var(--space-5);
  }
</style>

// src/components/SetupSheet.tsx
import { CheckCircle2, Footprints, Hand, RefreshCw, Smartphone, SwitchCamera } from 'lucide-react'
import { isFallback, type Framing, type HandsFreeStatus } from '@/handsfree/types'
import { useT } from '@/i18n'
import { cn } from '@/lib/cn'
import { CameraPreview, useFallbackText, useStatusText } from './HandsFree'
import { Sheet } from './ui/Sheet'
import { Button } from './ui/primitives'

/**
 * Getting hands-free right the first time: where to put the device, a live
 * framing check, and a way out (demo) if there's no camera.
 */
export function SetupSheet({
  open,
  onOpenChange,
  status,
  stream,
  framing,
  engineLabel,
  facingMode,
  onFlip,
  onRetry,
  onDemo,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  status: HandsFreeStatus
  stream: MediaStream | null
  framing: Framing
  engineLabel: string | null
  facingMode: 'user' | 'environment'
  onFlip: () => void
  onRetry: () => void
  onDemo: () => void
}) {
  const t = useT()
  const statusText = useStatusText()
  const fallback = useFallbackText()(status)
  const watching = status === 'watching'

  const check = !watching
    ? { tone: 'muted', text: statusText(status) }
    : framing === 'full'
      ? { tone: 'ok', text: t('setup.seeYou') }
      : framing === 'partial'
        ? { tone: 'warn', text: t('hf.msg.noPerson') }
        : { tone: 'muted', text: t('setup.lookingForYou') }

  const steps = [
    { icon: Smartphone, text: t('setup.step1') },
    { icon: Footprints, text: t('setup.step2') },
    { icon: Hand, text: t('setup.step3') },
  ]

  return (
    <Sheet open={open} onOpenChange={onOpenChange} title={t('setup.title')} description={t('setup.body')}>
      <div className="relative mt-2 overflow-hidden rounded-2xl border border-line bg-black/40">
        {stream ? (
          <CameraPreview stream={stream} mirror={facingMode === 'user'} className="aspect-[3/4] w-full sm:aspect-[4/5]" />
        ) : (
          <div className="grid aspect-[3/4] w-full place-items-center p-6 text-center text-sm text-ink-muted sm:aspect-[4/5]">
            {fallback ?? <span className="animate-breathe">{statusText(status)}</span>}
          </div>
        )}
        {/* A soft guide for where the body should be. */}
        {stream && (
          <div
            aria-hidden
            className={cn(
              'pointer-events-none absolute inset-x-[22%] inset-y-[8%] rounded-[45%_45%_18%_18%/30%_30%_10%_10%] border-2 border-dashed transition-colors duration-500',
              framing === 'full' ? 'border-mint/70' : 'border-white/30',
            )}
          />
        )}
        <div
          className={cn(
            'absolute inset-x-3 bottom-3 flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm backdrop-blur-md',
            check.tone === 'ok' ? 'bg-mint/20 text-mint' : check.tone === 'warn' ? 'bg-amber-400/15 text-amber-100' : 'bg-black/45 text-ink-soft',
          )}
        >
          {check.tone === 'ok' && <CheckCircle2 className="size-4" />}
          {check.text}
        </div>
        {stream && (
          <button
            onClick={onFlip}
            className="absolute end-3 top-3 flex size-10 cursor-pointer items-center justify-center rounded-full bg-black/45 text-ink backdrop-blur-md hover:bg-black/60"
            aria-label="Switch camera"
          >
            <SwitchCamera className="size-[18px]" />
          </button>
        )}
      </div>

      {engineLabel && status === 'watching' && (
        <p className="mt-2 text-center text-[11px] text-ink-faint">{engineLabel} · {t('hf.private')}</p>
      )}

      <ol className="mt-4 space-y-2.5">
        {steps.map(({ icon: Icon, text }, i) => (
          <li key={i} className="flex items-center gap-3 text-sm text-ink-soft">
            <span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-white/[0.06] text-mint">
              <Icon className="size-4" />
            </span>
            {text}
          </li>
        ))}
      </ol>

      <div className="mt-5 flex flex-col gap-2">
        {isFallback(status) && status !== 'no-model' ? (
          <Button variant="primary" size="lg" onClick={onRetry}>
            <RefreshCw className="size-4" />
            {t('hf.retry')}
          </Button>
        ) : (
          <Button variant="primary" size="lg" onClick={() => onOpenChange(false)}>
            {t('setup.done')}
          </Button>
        )}
        <Button variant="quiet" onClick={onDemo}>
          {t('setup.tryDemo')}
        </Button>
      </div>
    </Sheet>
  )
}
