// src/App.tsx
import { Settings2 } from 'lucide-react'
import { AnimatePresence, MotionConfig, motion } from 'motion/react'
import { AlertDialog, Direction, Tooltip as RadixTooltip } from 'radix-ui'
import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react'
import { CameraBubble, DemoBar, HandsFreeButton } from '@/components/HandsFree'
import { Logo } from '@/components/Logo'
import { useCompanionAudio } from '@/audio/use-companion-audio'
import { CompletePanel, ReadyPanel } from '@/components/Panels'
import { PostureDock } from '@/components/PostureDock'
import { PrayerChips, PrayerMenu } from '@/components/PrayerSelector'
import { Recitation } from '@/components/Recitation'
import { SettingsSheet } from '@/components/SettingsSheet'
import { SetupSheet } from '@/components/SetupSheet'
import { CHARACTERS, DEFAULT_CHARACTER } from '@/components/stage/characters'
import { Scenery } from '@/components/stage/Scenery'
import type { PoseName } from '@/components/stage/rig/prayer-poses'
import { Button } from '@/components/ui/primitives'
import { PRAYER_BY_ID } from '@/content/prayers'
import { isFollowing } from '@/handsfree/types'
import { useHandsFree } from '@/handsfree/use-hands-free'
import { LOCALES, useLocale, useT } from '@/i18n'
import { chime } from '@/lib/chime'
import { useMedia, useReducedMotion } from '@/lib/use-media'
import { usePrayerClock } from '@/lib/use-prayer-clock'
import { useWakeLock } from '@/lib/use-wake-lock'
import type { PrayerId, Step } from '@/sequence/types'
import { PACE_FACTOR, currentStep, useSession } from '@/state/session'

// The 3D stack is the heaviest part of the app; let the UI paint first.
const CompanionStage = lazy(() => import('@/components/stage/CompanionStage').then((m) => ({ default: m.CompanionStage })))

/** How long hands-free waits for a movement it cannot see before moving on anyway. */
const BODY_GRACE_MS = 6000

const stepMs = (step: Step, pace: keyof typeof PACE_FACTOR) => Math.max(step.timing.minMs, step.timing.expectedMs * PACE_FACTOR[pace])

export function App() {
  const t = useT()
  const locale = useLocale()
  const dir = LOCALES[locale].dir
  const clock = usePrayerClock()
  const session = useSession()
  const { phase, prayer, settings, handsFree, demo, index, sequence } = session
  const step = currentStep(session)
  const wide = useMedia('(min-width: 1024px)')
  const wideLayout = useMedia('(min-width: 1100px) and (min-aspect-ratio: 5/4)')
  const short = useMedia('(orientation: landscape) and (max-height: 540px)')
  const reducedMotion = useReducedMotion()
  const character = CHARACTERS.find((c) => c.id === settings.characterId) ?? DEFAULT_CHARACTER
  const [stageReady, setStageReady] = useState(false)
  const [pendingSwitch, setPendingSwitch] = useState<PrayerId | null>(null)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [setupOpen, setSetupOpen] = useState(false)
  const [facingMode, setFacingMode] = useState<'user' | 'environment'>('user')
  const [demoAuto, setDemoAuto] = useState(false)

  const hands = useHandsFree({ enabled: handsFree, demo, facingMode, onPose: session.onPose })
  const following = handsFree && isFollowing(hands.status)

  const toggleHandsFree = useCallback(() => {
    const s = useSession.getState()
    if (s.handsFree) return s.setHandsFree(false)
    s.setHandsFree(true)
    if (!s.demo) setSetupOpen(true)
  }, [])

  // Deep link: /?prayer=maghrib opens that prayer.
  useEffect(() => {
    const p = new URLSearchParams(location.search).get('prayer') as PrayerId | null
    if (p && p in PRAYER_BY_ID) useSession.getState().choosePrayer(p)
  }, [])

  // Language and direction for the whole document.
  useEffect(() => {
    document.documentElement.lang = locale
    document.documentElement.dir = dir
  }, [locale, dir])

  // Each prayer tints the room like its time of day.
  const ambient = PRAYER_BY_ID[prayer].ambient
  useEffect(() => {
    document.documentElement.dataset.prayer = prayer
  }, [prayer])

  useWakeLock(phase === 'praying')
  const { speaking, audioMs } = useCompanionAudio({ phase, step, next: sequence.steps[index + 1], prayer, voice: character.id, locale, settings })
  const timedMs = useStepTimer(following, audioMs)

  // Praying behind the companion: when it recites, it leads (pause any time).
  const leadOnBegin = useRef(phase)
  useEffect(() => {
    const s = useSession.getState()
    if (leadOnBegin.current === 'ready' && phase === 'praying' && settings.voice && !s.handsFree) s.setAutoplay(true)
    leadOnBegin.current = phase
  }, [phase, settings.voice])
  useKeyboard(toggleHandsFree)

  // A soft chime when PrayAlong follows a movement, so nobody has to look up.
  const posture: PoseName = phase === 'ready' ? 'rest' : phase === 'complete' ? 'jalsah' : step.posture
  const lastPosture = useRef(posture)
  useEffect(() => {
    if (posture !== lastPosture.current && following && settings.sounds && phase !== 'ready') chime()
    lastPosture.current = posture
  }, [posture, following, settings.sounds, phase])

  // The movement PrayAlong is waiting for next (guides the demo bar).
  const nextPose =
    phase === 'ready' ? 'hands-raised' : phase === 'praying' ? (sequence.steps.slice(index + 1).find((s) => s.pose !== step.pose)?.pose ?? null) : null

  // Demo autopilot: act out each movement once its lines are done.
  const actOut = hands.actOut
  useEffect(() => {
    if (!demo || !demoAuto || !handsFree) return
    if (phase === 'complete') return setDemoAuto(false)
    const after = sequence.steps[index + 1]
    if (phase === 'praying' && (!after || after.pose === step.pose)) return // lines advance on their own
    const delay = phase === 'ready' ? 1200 : stepMs(step, settings.pace)
    const id = setTimeout(() => nextPose && actOut(nextPose), delay)
    return () => clearTimeout(id)
  }, [demo, demoAuto, handsFree, phase, index, step, sequence, nextPose, settings.pace, actOut])

  return (
    <Direction.Provider dir={dir}>
      <MotionConfig reducedMotion="user">
        <RadixTooltip.Provider>
          <div className="relative flex h-full flex-col overflow-hidden bg-canvas">
            {/* Header */}
            <header className="relative z-20 flex h-16 shrink-0 items-center gap-3 px-4 sm:h-[4.5rem] sm:px-6 short:h-12">
              <div className="flex flex-1 items-center">
                <Logo compact={!wide} />
              </div>
              {wide ? <PrayerChips clock={clock} onRequestSwitch={setPendingSwitch} /> : <PrayerMenu clock={clock} onRequestSwitch={setPendingSwitch} />}
              <div className="flex flex-1 items-center justify-end gap-1.5 sm:gap-2">
                <Button variant="quiet" size="icon" aria-label={t('settings.title')} onClick={() => setSettingsOpen(true)}>
                  <Settings2 className="size-[18px]" />
                </Button>
                <HandsFreeButton on={handsFree} status={hands.status} onToggle={toggleHandsFree} compact={!wide} />
              </div>
            </header>

            {/* Stage */}
            <main className="relative flex min-h-0 flex-1 flex-col short:flex-row wide:flex-row">
              {/* The room spans the page; on wide screens its window sits behind the companion. */}
              {(wideLayout || short) && <Scenery prayer={prayer} windowX={dir === 'rtl' ? 100 - (wideLayout ? 26.5 : 24) : wideLayout ? 26.5 : 24} />}
              <div className="relative min-h-0 min-w-0 flex-1 wide:flex-[1.12]">
                <Suspense>
                  <CompanionStage
                    posture={posture}
                    character={character}
                    ambient={ambient}
                    prayer={prayer}
                    scenery={!(wideLayout || short)}
                    raiseHands={settings.raiseHands}
                    reducedMotion={reducedMotion}
                    onLoaded={() => setStageReady(true)}
                  />
                </Suspense>
                <AnimatePresence>
                  {!stageReady && (
                    <motion.div exit={{ opacity: 0 }} className="pointer-events-none absolute inset-0 grid place-items-center text-sm text-ink-faint">
                      <span className="animate-breathe">{t('stage.preparing')}</span>
                    </motion.div>
                  )}
                </AnimatePresence>
                <div className="pointer-events-none absolute inset-x-0 bottom-0 h-16 bg-gradient-to-t from-canvas to-transparent wide:hidden" />
                <div className="absolute end-3 top-3 z-10 sm:end-5 sm:top-4">
                  <AnimatePresence>
                    {handsFree && !setupOpen && (
                      <CameraBubble
                        stream={hands.stream}
                        status={hands.status}
                        pose={hands.pose}
                        framing={hands.framing}
                        onOpen={() => setSetupOpen(true)}
                        onRetry={hands.retry}
                        onDemo={() => session.setDemo(true)}
                      />
                    )}
                  </AnimatePresence>
                </div>
                <div className="absolute inset-x-0 bottom-3 z-10 flex justify-center px-3">
                  <AnimatePresence>
                    {handsFree && demo && <DemoBar current={hands.pose} expected={nextPose} auto={demoAuto} onAct={actOut} onAuto={setDemoAuto} />}
                  </AnimatePresence>
                </div>
              </div>

              <section className="relative z-10 flex min-h-[34%] shrink-0 items-start justify-center pb-3 short:min-h-0 short:w-[52%] short:items-center short:overflow-y-auto short:py-3 wide:min-h-0 wide:flex-1 wide:items-center wide:pe-[3vw] wide:ps-[1vw] wide:pb-0">
                <AnimatePresence mode="wait">
                  {phase === 'ready' && <ReadyPanel key="ready" clock={clock} handsFree={handsFree} onHandsFree={toggleHandsFree} />}
                  {phase === 'praying' && (
                    <motion.div key="praying" className="w-full" exit={{ opacity: 0 }}>
                      <Recitation step={step} next={sequence.steps[index + 1]} timedMs={timedMs} distance={following} speaking={speaking} />
                    </motion.div>
                  )}
                  {phase === 'complete' && <CompletePanel key="complete" clock={clock} />}
                </AnimatePresence>
              </section>
            </main>

            {/* Dock */}
            <footer className="relative z-10 shrink-0 px-3 pb-[max(0.75rem,env(safe-area-inset-bottom))] sm:px-6 sm:pb-6 short:pb-2">
              <PostureDock following={following} />
            </footer>
          </div>

          <SettingsSheet open={settingsOpen} onOpenChange={setSettingsOpen} clock={clock} />
          <SetupSheet
            open={setupOpen && handsFree && !demo}
            onOpenChange={setSetupOpen}
            status={hands.status}
            stream={hands.stream}
            framing={hands.framing}
            engineLabel={hands.engineLabel}
            facingMode={facingMode}
            onFlip={() => setFacingMode((m) => (m === 'user' ? 'environment' : 'user'))}
            onRetry={hands.retry}
            onDemo={() => {
              setSetupOpen(false)
              session.setDemo(true)
            }}
          />
          <SwitchPrayerDialog pending={pendingSwitch} onClose={() => setPendingSwitch(null)} />
        </RadixTooltip.Provider>
      </MotionConfig>
    </Direction.Provider>
  )
}

/**
 * Moves through lines on its own when the user asked for guidance, or when
 * hands-free is on (within a posture — the body decides when to move on).
 * Hands-free without a working camera falls back to timed guidance.
 * Returns the current line's duration so the UI can show a gentle timer.
 */
function useStepTimer(following: boolean, audioMs: number | null): number | null {
  const { phase, index, sequence, autoplay, handsFree, settings, next } = useSession()
  const step = sequence.steps[index]!
  const after = sequence.steps[index + 1]
  const timed = phase === 'praying' && (autoplay || handsFree)
  const waitForBody = following && after !== undefined && after.pose !== step.pose
  // When the companion recites, never cut it short; leave a breath after.
  const ms = audioMs !== null ? Math.max(audioMs + 700, step.timing.minMs) : stepMs(step, settings.pace)

  useEffect(() => {
    if (!timed) return
    // Waiting for the body: if the camera misses the movement, never stall;
    // carry on a few seconds after the line is done.
    const id = setTimeout(next, waitForBody ? ms + BODY_GRACE_MS : ms)
    return () => clearTimeout(id)
  }, [timed, waitForBody, ms, index, next])

  return timed && !waitForBody ? ms : null
}

function useKeyboard(toggleHandsFree: () => void) {
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.metaKey || e.ctrlKey || e.altKey) return
      const el = e.target as HTMLElement
      if (el.closest('input, textarea, [role="dialog"], [role="radiogroup"], [role="toolbar"]')) return
      const s = useSession.getState()
      const rtl = document.documentElement.dir === 'rtl'
      const forward = rtl ? 'ArrowLeft' : 'ArrowRight'
      const back = rtl ? 'ArrowRight' : 'ArrowLeft'
      if ((e.key === ' ' || e.key === 'Enter') && el.tagName === 'BUTTON') return // let the button handle it
      if (e.key === ' ' || e.key === forward || e.key === 'Enter') {
        e.preventDefault()
        s.next()
      } else if (e.key === back) {
        e.preventDefault()
        s.prev()
      } else if (e.key === 'p' || e.key === 'P') {
        if (!s.handsFree) s.setAutoplay(!s.autoplay)
      } else if (e.key === 'h' || e.key === 'H') {
        toggleHandsFree()
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [toggleHandsFree])
}

function SwitchPrayerDialog({ pending, onClose }: { pending: PrayerId | null; onClose: () => void }) {
  const t = useT()
  const { prayer, sequence, index, choosePrayer } = useSession()
  const rakah = sequence.steps[index]?.rakah ?? 1
  const to = pending ? t(`prayer.${pending}`) : ''
  return (
    <AlertDialog.Root open={pending !== null} onOpenChange={(open) => !open && onClose()}>
      <AlertDialog.Portal>
        <AlertDialog.Overlay className="sheet-overlay fixed inset-0 z-50 bg-black/60 backdrop-blur-sm" />
        <AlertDialog.Content className="fixed top-1/2 left-1/2 z-50 w-[min(24rem,calc(100vw-2rem))] -translate-x-1/2 -translate-y-1/2 animate-pop rounded-2xl border border-line bg-raised p-5 shadow-2xl">
          <AlertDialog.Title className="text-base font-semibold text-ink">{t('switch.title', { prayer: to })}</AlertDialog.Title>
          <AlertDialog.Description className="mt-1.5 text-sm leading-relaxed text-ink-soft">
            {t('switch.body', { r: rakah, from: t(`prayer.${prayer}`), to })}
          </AlertDialog.Description>
          <div className="mt-5 flex justify-end gap-2">
            <AlertDialog.Cancel asChild>
              <Button variant="quiet">{t('switch.keep')}</Button>
            </AlertDialog.Cancel>
            <AlertDialog.Action asChild>
              <Button variant="primary" onClick={() => pending && choosePrayer(pending)}>
                {t('switch.confirm')}
              </Button>
            </AlertDialog.Action>
          </div>
        </AlertDialog.Content>
      </AlertDialog.Portal>
    </AlertDialog.Root>
  )
}

// src/App.svelte
<script lang="ts">
  import Settings2 from '@lucide/svelte/icons/settings-2'
  import Video from '@lucide/svelte/icons/video'
  import VideoOff from '@lucide/svelte/icons/video-off'
  import { untrack } from 'svelte'
  import { expoOut } from 'svelte/easing'
  import { MediaQuery } from 'svelte/reactivity'
  import { fade, fly } from 'svelte/transition'
  import ConfirmDialog from '@/components/ConfirmDialog.svelte'
  import DemoBar from '@/components/DemoBar.svelte'
  import HandsFree from '@/components/HandsFree.svelte'
  import Mark from '@/components/Mark.svelte'
  import Panels from '@/components/Panels.svelte'
  import PostureDock from '@/components/PostureDock.svelte'
  import PrayerPicker from '@/components/PrayerPicker.svelte'
  import Recitation from '@/components/Recitation.svelte'
  import SettingsSheet from '@/components/SettingsSheet.svelte'
  import SetupSheet from '@/components/SetupSheet.svelte'
  import { characterById } from '@/components/stage/characters'
  import type { PoseName } from '@/components/stage/rig/prayer-poses'
  import Stage from '@/components/stage/Stage.svelte'
  import { handsFree } from '@/handsfree/hands-free.svelte'
  import { isFollowing } from '@/handsfree/types'
  import { i18n, t } from '@/i18n/i18n.svelte'
  import { applyPalette } from '@/lib/brand'
  import { chime } from '@/lib/chime'
  import { clock } from '@/lib/prayer-clock.svelte'
  import { holdWakeLock } from '@/lib/wake-lock'
  import type { PrayerId, Step } from '@/sequence/types'
  import { session, type Mode } from '@/state/session.svelte'
  import { resolveLine } from '@/content/lines'
  import { trackable } from '@/voice/asr/words'
  import { exampleOf, voice, type CoachKey } from '@/voice/voice.svelte'

  i18n.sync()
  // Start on the prayer that is due, so the first paint loads the right backdrop.
  session.autoSelectPrayer(clock.detected.id)
  clock.start()

  const wide = new MediaQuery('min-width: 1200px')
  const reducedMotion = new MediaQuery('prefers-reduced-motion: reduce')

  let pendingSwitch = $state<PrayerId | null>(null)
  let settingsOpen = $state(false)
  let setupOpen = $state(false)
  let demoAuto = $state(false)

  const character = $derived(characterById(session.settings.characterId))
  const following = $derived(session.handsFree && isFollowing(handsFree.status))
  const step = $derived(session.step)
  const posture: PoseName = $derived(session.phase === 'ready' ? 'rest' : session.phase === 'complete' ? 'jalsah' : step.posture === 'tashahhud' && step.rakah === session.sequence.rakahs ? 'tawarruk' : step.posture)
  const stepMs = (s: Step) => Math.max(s.timing.minMs, s.timing.expectedMs)

  // ——— hands-free
  handsFree.onPose = (pose) => session.onPose(pose)
  handsFree.connect(() => ({ enabled: session.handsFree, demo: session.demo }))
  // Developers and tests without a camera: ?demo drives hands-free from on-screen buttons.
  const devDemo = new URLSearchParams(location.search).has('demo')

  /** One prompt for the camera and the microphone, before either is opened. */
  async function askForCameraAndMic() {
    const audio = globalThis.crossOriginIsolated === true
    try {
      const media = await navigator.mediaDevices.getUserMedia({ video: true, audio })
      media.getTracks().forEach((track) => track.stop())
    } catch {
      /* each one asks again on its own, and falls back on its own */
    }
  }

  /** The learner picked how to pray: set up the camera (hands-free is on by default), then begin. */
  async function start(mode: Mode) {
    session.mode = mode
    if (session.settings.handsFree && devDemo) session.setDemo(true)
    else if (session.settings.handsFree) {
      setupOpen = true
      await askForCameraAndMic()
      session.setHandsFree(true)
    }
    void voice.listen() // follows the recitation wherever the browser can run it
    if (!session.settings.handsFree || devDemo) session.begin()
  }

  function toggleHandsFree() {
    const on = !session.settings.handsFree
    session.updateSettings({ handsFree: on })
    if (!on) return session.setHandsFree(false)
    if (session.phase === 'ready') return
    session.setHandsFree(true)
    setupOpen = true
  }
  // Raising the hands begins the prayer: the setup sheet steps aside.
  let lastPhase = session.phase
  $effect(() => {
    if (lastPhase === 'ready' && session.phase === 'praying') setupOpen = false
    lastPhase = session.phase
  })

  // ——— document language, direction, theme and colour; after the first paint, a change crossfades
  let painted = false
  function morph(change: () => void) {
    if (!painted || reducedMotion.current || !document.startViewTransition) return change()
    document.startViewTransition(change)
  }
  $effect(() => {
    const { locale, dir } = i18n
    morph(() => {
      document.documentElement.lang = locale
      document.documentElement.dir = dir
    })
  })
  $effect(() => {
    const theme = session.settings.theme
    morph(() => {
      if (theme === 'system') delete document.documentElement.dataset.theme
      else document.documentElement.dataset.theme = theme
    })
  })
  $effect(() => {
    const palette = session.settings.palette
    morph(() => applyPalette(palette))
  })
  $effect(() => {
    painted = true
  })

  $effect(() => {
    if (session.phase === 'praying') return holdWakeLock()
  })

  // ——— timed guidance: on request, or within a posture while hands-free follows the body
  const after = $derived(session.sequence.steps[session.index + 1])
  const timed = $derived(session.phase === 'praying' && (session.autoplay || session.handsFree))
  const waitForBody = $derived(following && after !== undefined && after.pose !== step.pose)

  // ——— voice: the coach says the movement and what to recite, then (watching first) the example
  // plays, then it is the learner's turn. Everything is spoken, so nobody has to read from the mat.
  let instructing = $state(false)
  let listening = $state(false)
  let turn = $state(false)
  const line = $derived(session.phase === 'praying' ? resolveLine(step.recitationId, i18n.locale) : null)
  const hearing = $derived(voice.asr === 'on' && line !== null && trackable(step.recitationId) && step.voice === 'aloud')
  const heard = $derived(hearing && line ? voice.heard(step.recitationId, line.arabic) : 0)
  const heardAll = $derived(hearing && line !== null && heard >= line.arabic.split(/\s+/).filter(Boolean).length)

  /** Speak a coach line: the rendered English clip, or the browser's voice for `voice.say.*`. */
  const say = (key: CoachKey, signal: AbortSignal) => voice.coach(key, i18n.locale, t(`voice.say.${key}`), signal)
  /** The coach line for a movement: standing up names the rak'ah. */
  const coachKey = (cue: string, rakah: number) => (cue === 'rise' ? `rise${rakah}` : cue) as CoachKey
  const pause = (ms: number, signal: AbortSignal) =>
    new Promise<void>((resolve) => {
      const id = setTimeout(resolve, ms)
      signal.addEventListener('abort', () => (clearTimeout(id), resolve()), { once: true })
    })

  // Each line: the movement (unless it was said ahead) and what to recite; when watching first,
  // the example; then the learner's turn. "Listen first" and "Now you" frame the first example.
  let saidAhead: string | null = null
  let heardExample = false
  $effect(() => {
    if (session.phase !== 'praying') return
    const s = step
    const ac = new AbortController()
    listening = false
    turn = false
    voice.newLine()
    untrack(() => {
      void (async () => {
        instructing = true
        const opening = session.index === 0 && saidAhead !== s.id
        if (opening) heardExample = false
        if (opening) await say('face', ac.signal)
        if (s.cue && saidAhead !== s.id) await say(coachKey(s.cue, s.rakah), ac.signal)
        if (s.say) await say(s.say, ac.signal)
        if (ac.signal.aborted) return
        instructing = false
        if (session.mode !== 'watch' || !exampleOf(s.recitationId)) return
        const first = !heardExample
        heardExample = true
        if (first) await say('listen', ac.signal)
        listening = true
        await voice.example(s.recitationId, ac.signal)
        if (ac.signal.aborted) return
        listening = false
        turn = true
        voice.newLine()
        if (first) await say('yourTurn', ac.signal)
      })()
    })
    return () => ac.abort()
  })

  // Following the body: once a block's lines are done, say the next movement before the learner makes it.
  $effect(() => {
    if (!waitForBody || listening || instructing || !after?.cue) return
    const ac = new AbortController()
    const next = after
    const id = setTimeout(() => {
      saidAhead = next.id
      void say(coachKey(next.cue!, next.rakah), ac.signal)
    }, heardAll ? 400 : stepMs(step))
    return () => {
      clearTimeout(id)
      ac.abort()
    }
  })

  // Hands-free, ready to begin: tell the learner how to stand and how to start.
  $effect(() => {
    if (session.phase !== 'ready' || !following) return
    const ac = new AbortController()
    void (async () => {
      await pause(800, ac.signal)
      if (ac.signal.aborted) return
      saidAhead = session.sequence.steps[0]?.id ?? null
      heardExample = false
      await say('face', ac.signal)
      await say('begin', ac.signal)
    })()
    return () => ac.abort()
  })
  // The prayer is complete: the remembrance right after it, with its example when watching first.
  $effect(() => {
    if (session.phase !== 'complete') return
    const ac = new AbortController()
    const watching = untrack(() => session.mode === 'watch')
    void (async () => {
      await say('complete', ac.signal)
      await say('afterPrayer', ac.signal)
      if (!watching || ac.signal.aborted) return
      await voice.example('istighfar', ac.signal)
      await pause(4500, ac.signal) // the learner's three times
      if (!ac.signal.aborted) await voice.example('antas-salam', ac.signal)
    })()
    return () => ac.abort()
  })

  // Following the recitation is part of praying with PrayAlong: the microphone opens with the prayer.
  $effect(() => {
    if (session.phase === 'praying') untrack(() => void voice.listen())
  })

  // The line's time starts after the qari. A line the ASR heard in full moves on a moment later.
  const timedMs = $derived(timed && !waitForBody && !listening && !instructing ? (heardAll ? 700 : stepMs(step)) : null)
  $effect(() => {
    if (timedMs === null) return
    void session.index
    const id = setTimeout(() => session.next(), timedMs)
    return () => clearTimeout(id)
  })

  // A soft chime when PrayAlong follows a movement, so nobody has to look up.
  let lastPosture: PoseName = 'rest'
  $effect(() => {
    if (posture !== lastPosture && following && session.phase !== 'ready') chime()
    lastPosture = posture
  })

  // The movement PrayAlong is waiting for next (guides the demo bar).
  const nextPose = $derived(
    session.phase === 'ready' ? 'hands-raised' : session.phase === 'praying' ? (session.sequence.steps.slice(session.index + 1).find((s) => s.pose !== step.pose)?.pose ?? null) : null,
  )

  // Demo autopilot: act out each movement once its lines are done.
  $effect(() => {
    if (!session.demo || !demoAuto || !session.handsFree) return
    if (session.phase === 'complete') return void (demoAuto = false)
    if (session.phase === 'praying' && (!after || after.pose === step.pose)) return // lines advance on their own
    const delay = session.phase === 'ready' ? 1200 : stepMs(step)
    const pose = nextPose
    const id = setTimeout(() => pose && handsFree.actOut(pose), delay)
    return () => clearTimeout(id)
  })

  function onKey(e: KeyboardEvent) {
    if (e.metaKey || e.ctrlKey || e.altKey) return
    const el = e.target as HTMLElement
    if (el.closest('input, textarea, dialog, [role="radiogroup"], [role="toolbar"], [popover]')) return
    const rtl = document.documentElement.dir === 'rtl'
    if ((e.key === ' ' || e.key === 'Enter') && el.tagName === 'BUTTON') return // let the button handle it
    if (e.key === ' ' || e.key === (rtl ? 'ArrowLeft' : 'ArrowRight') || e.key === 'Enter') {
      e.preventDefault()
      if (session.phase === 'ready') void start(session.mode)
      else session.next()
    } else if (e.key === (rtl ? 'ArrowRight' : 'ArrowLeft')) {
      e.preventDefault()
      session.prev()
    } else if (e.key === 'p' || e.key === 'P') {
      if (!session.handsFree) session.setAutoplay(!session.autoplay)
    } else if (e.key === 'h' || e.key === 'H') toggleHandsFree()
  }
</script>

<svelte:window onkeydown={onKey} />

<div class="app">
  <header class="top">
    <a class="brand" href="./" aria-label="PrayAlong">
      <Mark size={20} />
      <span class="hide-phone">PrayAlong</span>
    </a>
    <PrayerPicker wide={wide.current} onrequestswitch={(id) => (pendingSwitch = id)} />
    <div class="actions">
      <button type="button" class="btn sm label" onclick={() => (settingsOpen = true)} aria-label={t('header.settings')}>
        <Settings2 size={18} /><span class="hide-narrow">{t('header.settings')}</span>
      </button>
      <button type="button" class="btn sm label" aria-pressed={session.settings.handsFree} onclick={toggleHandsFree} title="{session.settings.handsFree ? t('hf.tipOn') : t('hf.tipOff')} {t('hf.private')} (H)">
        {#if session.settings.handsFree}<Video size={18} />{:else}<VideoOff size={18} />{/if}
        <span class="hide-narrow">{t('hf.button')}</span>
        {#if following}<i class="live" aria-hidden="true"></i>{/if}
      </button>
    </div>
  </header>

  <main>
    <div class="stage-area">
      <Stage prayer={session.prayer} {posture} {character} palette={session.settings.palette} reducedMotion={reducedMotion.current}>
        <div class="overlay top-end">
          {#if session.handsFree && !setupOpen}
            <HandsFree onopen={() => (setupOpen = true)} />
          {/if}
        </div>
        <div class="overlay bottom">
          {#if session.handsFree && session.demo}
            <DemoBar current={handsFree.pose} expected={nextPose} auto={demoAuto} onact={handsFree.actOut} onauto={(on) => (demoAuto = on)} />
          {/if}
        </div>
      </Stage>
    </div>

    <!-- Ready, praying and complete share one place: each arrives as the last one leaves. -->
    <section class="words" class:complete={session.phase === 'complete'}>
      {#key session.phase}
        <div class="phase" in:fly={{ y: 10, duration: 420, delay: 140, easing: expoOut }} out:fade={{ duration: 140 }}>
          {#if session.phase === 'praying'}
            <Recitation {timedMs} distance={following} {listening} {turn} {heard} {hearing} />
          {:else}
            <Panels kind={session.phase} onstart={start} />
          {/if}
        </div>
      {/key}
    </section>
  </main>

  <footer>
    <PostureDock {following} />
  </footer>
</div>

<SettingsSheet bind:open={settingsOpen} />
<SetupSheet
  bind:open={() => setupOpen && session.settings.handsFree && !session.demo, (v) => (setupOpen = v)}
  onbegin={() => {
    setupOpen = false
    if (session.phase === 'ready') session.begin()
  }}
/>
<ConfirmDialog bind:pending={pendingSwitch} />

<style>
  .app {
    /* One column for the header, the photograph, the line and the dock, so their edges line up;
       one gap between them. */
    --column: 1200px;
    --gap: var(--space-4);
    display: flex;
    flex-direction: column;
    height: 100%;
    height: 100dvh;
    /* clip, not hidden: focus and scrollIntoView must never scroll the whole app. */
    overflow: clip;
  }
  .top,
  main,
  footer {
    width: min(100% - 2 * var(--gutter), var(--column));
    margin-inline: auto;
  }
  .top {
    flex: none;
    display: grid;
    grid-template-columns: 1fr auto 1fr;
    align-items: center;
    gap: var(--space-3);
    height: 64px;
  }
  .brand {
    display: inline-flex;
    align-items: center;
    gap: 10px;
    justify-self: start;
    color: var(--ink);
    font-size: 17px;
    font-weight: 600;
    text-decoration: none;
  }
  .actions {
    display: flex;
    justify-self: end;
    gap: var(--space-2);
  }
  .label {
    position: relative;
  }
  .live {
    position: absolute;
    top: 6px;
    inset-inline-end: 6px;
    width: 6px;
    height: 6px;
    border-radius: var(--radius-full);
    background: var(--brand);
  }
  main {
    flex: 1;
    min-height: 0;
    display: flex;
    flex-direction: column;
    gap: var(--gap);
  }
  .stage-area {
    flex: 1 1 0;
    min-height: max(160px, 26svh);
  }
  .overlay {
    position: absolute;
    z-index: 10;
  }
  .top-end {
    top: 12px;
    inset-inline-end: 12px;
  }
  .bottom {
    inset-inline: 0;
    bottom: 12px;
    display: flex;
    justify-content: center;
    padding-inline: 12px;
  }
  /* The same height for every line and both panels: the photograph above never moves while
     praying. Text fits itself to it (lib/fit.ts). */
  .words {
    flex: 0 1 auto;
    height: clamp(220px, 52%, 460px);
    min-height: 200px;
    display: grid;
    grid-template: minmax(0, 1fr) / minmax(0, 1fr);
  }
  .phase {
    grid-area: 1 / 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
  }
  footer {
    flex: none;
    padding-block: var(--gap) max(var(--gap), env(safe-area-inset-bottom));
  }
  @media (max-width: 719px) {
    .hide-narrow {
      display: none;
    }
    .label {
      width: 40px;
      padding: 0;
    }
  }
  @media (max-width: 479px) {
    .hide-phone {
      display: none;
    }
    .app {
      --gap: var(--space-3);
    }
    .top {
      height: 56px;
    }
    .words {
      height: clamp(200px, 56%, 460px);
      transition: height 520ms cubic-bezier(0.32, 0.72, 0, 1);
    }
    /* After the prayer the photograph steps back for the remembrance. */
    .words.complete {
      height: clamp(200px, 74%, 580px);
    }
  }
  /* Phones on their side: stage and words side by side. */
  @media (orientation: landscape) and (max-height: 540px) {
    .top {
      height: 48px;
    }
    main {
      flex-direction: row;
    }
    .stage-area {
      min-height: 0;
    }
    .words {
      flex: none;
      width: 52%;
      height: auto;
      min-height: 0;
    }
    footer {
      padding-block: 8px;
    }
  }
</style>
